define([], function() {
  return {
    "Save": "Save",
    "SaveAndSubmit": "Save and submit",
    "Cancel": "Cancel",
    "Close": "Close",
    "Loading": "Loading form…",
    "Saving": "Saving…",
    "Ok": "OK",
    "ConfirmTitle": "Confirm",

    "LoadErrorTitle": "The form cannot be loaded.",
    "LoadErrorConfig": "The form configuration is invalid: {message}",
    "BackToList": "Back to the list",
    "ValidationSummary": "The form contains invalid or missing data. Please correct the highlighted fields.",
    "SaveErrorTitle": "Saving failed: {message}",
    "ConcurrencyError": "Someone else changed this item in the meantime. Reload the form and repeat your changes.",
    "Reload": "Reload",
    "AttachmentErrors": "The item was saved, but some attachment operations failed: {files}",

    "Required": "This field is required.",
    "Number": "Enter a number.",
    "Integer": "Enter a whole number.",
    "Date": "Enter a valid date.",
    "MaxLength": "Enter at most {maxLength} characters.",
    "Regex": "The value has an invalid format.",
    "Range": "The value must be between {minimum} and {maximum}.",
    "Compare": "The value is invalid.",
    "Custom": "The value is invalid.",
    "Rule": "The value is invalid.",
    "MaxEntities": "You can select at most {maximum} people.",
    "MinAttachments": "Attach at least {minimum} file(s).",
    "MaxAttachments": "You can attach at most {maximum} file(s).",
    "FileType": "Files of type .{extension} are not allowed.",
    "FileSize": "The file is too large (at most {maximum} bytes).",
    "Server": "SharePoint rejected the value.",

    "SelectPlaceholder": "Select…",
    "EmptyOption": "(none)",
    "SpecifyOwnValue": "Specify your own value:",
    "PeoplePickerPlaceholder": "Enter a name or email address…",
    "LookupLoading": "Loading…",
    "LookupLoadError": "The options cannot be loaded.",
    "AttachFile": "Attach file",
    "RemoveAttachment": "Remove",
    "NoAttachments": "No attachments.",
    "PendingUpload": "(uploaded when saved)",
    "UnsupportedControl": "Unsupported control: {type}",

    "DatePlaceholder": "Select a date…",
    "GoToToday": "Go to today",
    "PrevMonth": "Previous month",
    "NextMonth": "Next month",
    "Months": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    "ShortMonths": ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    "Days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    "ShortDays": ["S", "M", "T", "W", "T", "F", "S"],

    "DiagnosticsButton": "Diagnostics",
    "DiagnosticsTitle": "Form diagnostics",
    "DiagnosticsTab": "Diagnostics",
    "RuleTraceTab": "Rule trace",
    "ShowControlIds": "Show control ids",
    "NoDiagnostics": "No diagnostics.",
    "ColumnLevel": "Level",
    "ColumnCode": "Code",
    "ColumnMessage": "Message",
    "ColumnControl": "Control",
    "ColumnRule": "Rule",
    "ColumnResult": "Result"
  };
});
