define([], function() {
  return {
    "Save": "Mentés",
    "SaveAndSubmit": "Mentés és beküldés",
    "Cancel": "Mégse",
    "Close": "Bezárás",
    "Loading": "Űrlap betöltése…",
    "Saving": "Mentés folyamatban…",
    "Ok": "OK",
    "ConfirmTitle": "Megerősítés",

    "LoadErrorTitle": "Az űrlap nem tölthető be.",
    "LoadErrorConfig": "Az űrlap konfigurációja hibás: {message}",
    "BackToList": "Vissza a listához",
    "ValidationSummary": "Az űrlap hibás vagy hiányzó adatokat tartalmaz. Kérjük, javítsa a megjelölt mezőket.",
    "SaveErrorTitle": "A mentés nem sikerült: {message}",
    "ConcurrencyError": "Az elemet időközben valaki más módosította. Töltse újra az űrlapot, és ismételje meg a módosítást.",
    "Reload": "Újratöltés",
    "AttachmentErrors": "Az elem mentése sikerült, de néhány melléklet művelet hibára futott: {files}",

    "Required": "Kötelező mező.",
    "Number": "Számot adjon meg.",
    "Integer": "Egész számot adjon meg.",
    "Date": "Érvényes dátumot adjon meg.",
    "MaxLength": "Legfeljebb {maxLength} karakter adható meg.",
    "Regex": "Az érték formátuma nem megfelelő.",
    "Range": "Az értéknek {minimum} és {maximum} között kell lennie.",
    "Compare": "Az érték nem megfelelő.",
    "Custom": "Az érték nem megfelelő.",
    "Rule": "Az érték nem megfelelő.",
    "MaxEntities": "Legfeljebb {maximum} személy választható.",
    "MinAttachments": "Legalább {minimum} mellékletet csatoljon.",
    "MaxAttachments": "Legfeljebb {maximum} melléklet csatolható.",
    "FileType": "A(z) .{extension} fájltípus nem engedélyezett.",
    "FileSize": "A fájl túl nagy (legfeljebb {maximum} bájt).",
    "Server": "A SharePoint elutasította az értéket.",

    "SelectPlaceholder": "Válasszon…",
    "EmptyOption": "(nincs)",
    "SpecifyOwnValue": "Saját érték megadása:",
    "PeoplePickerPlaceholder": "Írjon be egy nevet vagy e-mail címet…",
    "LookupLoading": "Betöltés…",
    "LookupLoadError": "A választható értékek nem tölthetők be.",
    "AttachFile": "Fájl csatolása",
    "RemoveAttachment": "Eltávolítás",
    "NoAttachments": "Nincs melléklet.",
    "PendingUpload": "(mentéskor kerül feltöltésre)",
    "UnsupportedControl": "Nem támogatott vezérlő: {type}",

    "DatePlaceholder": "Válasszon dátumot…",
    "GoToToday": "Ugrás a mai napra",
    "PrevMonth": "Előző hónap",
    "NextMonth": "Következő hónap",
    "Months": ["január", "február", "március", "április", "május", "június", "július", "augusztus", "szeptember", "október", "november", "december"],
    "ShortMonths": ["jan.", "febr.", "márc.", "ápr.", "máj.", "jún.", "júl.", "aug.", "szept.", "okt.", "nov.", "dec."],
    "Days": ["vasárnap", "hétfő", "kedd", "szerda", "csütörtök", "péntek", "szombat"],
    "ShortDays": ["V", "H", "K", "Sze", "Cs", "P", "Szo"],

    "DiagnosticsButton": "Diagnosztika",
    "DiagnosticsTitle": "Űrlap diagnosztika",
    "DiagnosticsTab": "Diagnosztikák",
    "RuleTraceTab": "Szabály-nyomkövetés",
    "ShowControlIds": "Vezérlő-azonosítók megjelenítése",
    "NoDiagnostics": "Nincs diagnosztikai bejegyzés.",
    "ColumnLevel": "Szint",
    "ColumnCode": "Kód",
    "ColumnMessage": "Üzenet",
    "ColumnControl": "Vezérlő",
    "ColumnRule": "Szabály",
    "ColumnResult": "Eredmény"
  };
});
